/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './__root'
import { Route as AgentPopoverImport } from './agent-popover'
import { Route as AuthPathnameImport } from './auth/$pathname'
import { Route as ChatImport } from './chat'
import { Route as HistoryImport } from './history'
import { Route as IndexImport } from './index'
import { Route as SettingsImport } from './settings'
import { Route as VisionAutomateImport } from './vision-automate'

// Create/Update Routes

const SettingsRoute = SettingsImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRoute,
} as any)

const HistoryRoute = HistoryImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRoute,
} as any)

const ChatRoute = ChatImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRoute,
} as any)

const AgentPopoverRoute = AgentPopoverImport.update({
  id: '/agent-popover',
  path: '/agent-popover',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AuthPathnameRoute = AuthPathnameImport.update({
  id: '/auth/$pathname',
  path: '/auth/$pathname',
  getParentRoute: () => rootRoute,
} as any)

const VisionAutomateRoute = VisionAutomateImport.update({
  id: '/vision-automate',
  path: '/vision-automate',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/agent-popover': {
      id: '/agent-popover'
      path: '/agent-popover'
      fullPath: '/agent-popover'
      preLoaderRoute: typeof AgentPopoverImport
      parentRoute: typeof rootRoute
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatImport
      parentRoute: typeof rootRoute
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryImport
      parentRoute: typeof rootRoute
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsImport
      parentRoute: typeof rootRoute
    }
    '/auth/$pathname': {
      id: '/auth/$pathname'
      path: '/auth/$pathname'
      fullPath: '/auth/$pathname'
      preLoaderRoute: typeof AuthPathnameImport
      parentRoute: typeof rootRoute
    }
    '/vision-automate': {
      id: '/vision-automate'
      path: '/vision-automate'
      fullPath: '/vision-automate'
      preLoaderRoute: typeof VisionAutomateImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agent-popover': typeof AgentPopoverRoute
  '/chat': typeof ChatRoute
  '/history': typeof HistoryRoute
  '/settings': typeof SettingsRoute
  '/auth/$pathname': typeof AuthPathnameRoute
  '/vision-automate': typeof VisionAutomateRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agent-popover': typeof AgentPopoverRoute
  '/chat': typeof ChatRoute
  '/history': typeof HistoryRoute
  '/settings': typeof SettingsRoute
  '/auth/$pathname': typeof AuthPathnameRoute
  '/vision-automate': typeof VisionAutomateRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/agent-popover': typeof AgentPopoverRoute
  '/chat': typeof ChatRoute
  '/history': typeof HistoryRoute
  '/settings': typeof SettingsRoute
  '/auth/$pathname': typeof AuthPathnameRoute
  '/vision-automate': typeof VisionAutomateRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agent-popover'
    | '/chat'
    | '/history'
    | '/settings'
    | '/auth/$pathname'
    | '/vision-automate'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agent-popover'
    | '/chat'
    | '/history'
    | '/settings'
    | '/auth/$pathname'
    | '/vision-automate'
  id:
    | '__root__'
    | '/'
    | '/agent-popover'
    | '/chat'
    | '/history'
    | '/settings'
    | '/auth/$pathname'
    | '/vision-automate'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentPopoverRoute: typeof AgentPopoverRoute
  ChatRoute: typeof ChatRoute
  HistoryRoute: typeof HistoryRoute
  SettingsRoute: typeof SettingsRoute
  AuthPathnameRoute: typeof AuthPathnameRoute
  VisionAutomateRoute: typeof VisionAutomateRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentPopoverRoute: AgentPopoverRoute,
  ChatRoute: ChatRoute,
  HistoryRoute: HistoryRoute,
  SettingsRoute: SettingsRoute,
  AuthPathnameRoute: AuthPathnameRoute,
  VisionAutomateRoute: VisionAutomateRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/agent-popover",
        "/chat",
        "/history",
        "/settings",
        "/auth/$pathname",
        "/vision-automate"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/agent-popover": {
      "filePath": "agent-popover.tsx"
    },
    "/chat": {
      "filePath": "chat.tsx"
    },
    "/history": {
      "filePath": "history.tsx"
    },
    "/settings": {
      "filePath": "settings.tsx"
    },
    "/auth/$pathname": {
      "filePath": "auth/$pathname.tsx"
    },
    "/vision-automate": {
      "filePath": "vision-automate.tsx"
    }
  }
}
ROUTE_MANIFEST_END */